@startsalt UC39-editar-usuario-wireframe
{
  <b>Editar Usuario
  ..
  {
    Nombre | "Marta López"
    Correo | "marta@empresa.com"
    Rol    | ^Agente de Soporte^
    Equipo | ^Infraestructura^
  }
  ..
  [Cancelar] | [Guardar Cambios]
}
@endsalt
