@startuml UC29-editar-equipo
hide empty description

state "EQUIPO_EXISTENTE" as Pre
state "editarEquipo()" as UC {
  [*] --> fin
  fin --> [*]
}
state "EQUIPO_ACTUALIZADO" as Post

Pre --> UC : <b>Administrador</b> modifica el nombre
UC --> Post : <b>Sistema</b> actualiza el Equipo
@enduml
