@startsalt UC21-crear-categoria-wireframe
{
  <b>Crear Categoría
  ..
  {#
    Nombre  | "                              "
    Equipo  | ^Sin asignar^
  }
  ..
  [Cancelar] | [Crear Categoría]
}
@endsalt
